### ISSUE TITLE
Doesn't work on my inputs

### ISSUE THREAD

**Issue by bhollan** [dannybres/Advent-of-Code#1]
https://github.com/dannybres/Advent-of-Code/blob/d130d28c3bb84484742edc267996d7cb97f09d80/2024/Day%2016/day16puzzle1.m#L1

Hi! Thanks for sharing your code! You don't know me, but I first learned Matlab over a decade ago (closer to 2!!). I've since spent a LONG time in Python and R and can debug those pretty faithfully. However, I was struggling with this day of AOC and checked out your code and I'm learning a lot, even still!

I'm not that great a programmer, so I'm kind of used to my code working on the sample inputs and then not working on the full input. Then I have to figure out all the typically many edge cases that are in the full input that aren't in the sample or whatever. However, your code as posted here doesn't work on my full input (even though it works on both sample inputs). 

Do you have thoughts on that? 

I have other Matlab questions if you're up for preventing me from asking Mathworks a dumb question.

**Comment by dannybres** [comment]
How curious, my part one should work ok its just a simple Dijkstra, I cannot think of any reason it would fail. Could you share your input? daniel [at] breslan [dot] co [dot] uk

If I were to do it again, I would not combine the turns with their next step, I would split them to simplify the code a bit. However this would be less optimal I think as you would end up turning to face a wall, so maybe I wouldn't?

I do love MATLAB, fire the question to me! As an aside, what you se here  is my latest implementation of a priority queue in MATLAB, I am not convinced it is the best way yet. I am a mod on a MATLAB discord, if that is any use to you too. We can dm there too: https://discord.gg/967J6Cdn

**Comment by bhollan** [comment]
Email sent w/ files!
I've always assumed the AoC inputs are generated by code that gets pretty rigorously tested. I'd be pretty stoked to find a bug. But somehow I think the odds of the bug being in AoC rather than something stupid I did are pretty low.

**Comment by bhollan** [comment]
I think this line:
https://github.com/dannybres/Advent-of-Code/commit/eb1dccf7a528c4d246718ba0d20928c121db70bc#diff-856232b693d8512426c978ff168115e5ae2796610fdb25263aa8da6d7011c601R23

...is the only part of the changes I don't "get", but I'll take a deeper look as I step through everything again. Thanks!
